### PR TITLE
New suffixes for EPI fieldmapping

### PR DESCRIPTION
**Pull request by bkossows**
So I've modified the files manually by adding the two suffixes. Please let me know if I am wrong but I believe that is all.

### CODE REVIEW

**Comment by mslw** [comment]
Thanks! I think you're absolutely right with the xib part (my bad - thought it would be more complicated).

I don't quite like the change to series (it would put direction after run, while the [specs](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#case-4-multiple-phase-encoded-directions-pepolar) have it other way round). I have a slightly different idea for how to do this - if you don't mind, I'll try it and add here,  which would revert 3ef108b.

**Comment by mslw** [comment]
Hey, it looks like the PR comes from your master branch and I cannot push my changes to it. I'll make a PR to your master branch, when merged there it should update here (I think).

**Comment by bkossows** [comment]
Reverse push to Your repo :)

**Comment by mslw** [comment]
Since this is ready to test but may need small tweaks, let's put it in another branch where both of us have access.

**Pull request merged**
